version: "3.9"

services:
  roundtable:
    image: roundtable
    build:
      args:
        NEXT_PUBLIC_NETWORK: ${NETWORK:-preview}
        NEXT_PUBLIC_GRAPHQL: ${NEXT_PUBLIC_GRAPHQL:-graphql:3100}
        NEXT_PUBLIC_SUBMIT: ${NEXT_PUBLIC_SUBMIT:-https://testnet.tx.lidonation.com/}
        NEXT_PUBLIC_GUN: ${NEXT_PUBLIC_GUN:-}
    ports:
      - ${ROUNDTABLE_PORT:-3000}:3000
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      NEXT_PUBLIC_GRAPHQL: ${NEXT_PUBLIC_GRAPHQL:-graphql:3100}
      NEXT_PUBLIC_GUN:
      NEXT_PUBLIC_NETWORK: ${NETWORK:-preview}
      NEXT_PUBLIC_SUBMIT: ${NEXT_PUBLIC_SUBMIT:-https://testnet.tx.lidonation.com/}
  postgres:
    image: postgres:${POSTGRES_VERSION:-11.8-alpine}
    environment:
      - POSTGRES_LOGGING=true
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
    shm_size: '2gb'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  cardano-node-ogmios:
    image: cardanosolutions/cardano-node-ogmios:${OGMIOS_VERSION:-v5.6.0}_${CARDANO_NODE_VERSION:-1.35.5}-${NETWORK:-preview}
    platform: ${PLATFORM:-linux/x86_64}
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    ports:
      - ${OGMIOS_PORT:-1337}:1337
    restart: on-failure
    volumes:
      - ./data/cardano/cnode/db:/db:delegated
      - node-ipc:/ipc
      - ./config/network/${NETWORK:-preview}:/config/cardano-node

  cardano-db-sync:
    image: inputoutput/cardano-db-sync:${CARDANO_DB_SYNC_VERSION:-13.1.0.2}
    platform: ${PLATFORM:-linux/x86_64}
    command: [
      "--config", "/config/cardano-node/db-sync-config.json",
      "--socket-path", "/node-ipc/node.socket"
    ]
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - RESTORE_SNAPSHOT=${RESTORE_SNAPSHOT:-}
      - RESTORE_RECREATE_DB=N
    depends_on:
      - cardano-node-ogmios
      - postgres
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - ./config/network/${NETWORK:-preview}:/config/cardano-node
      - db-sync-data:/var/lib/cexplorer
      - node-ipc:/node-ipc
    restart: on-failure
    stop_signal: SIGINT
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  cardano-graphql-background:
    image: inputoutput/cardano-graphql-background:${CARDANO_GRAPHQL_BACKROUND_VERSION:-8.0.0}-${NETWORK:-preview}
    platform: ${PLATFORM:-linux/x86_64}
#    command: [
#      "--config", "/config/cardano-node/db-sync-config.json",
#      "--socket-path", "/node-ipc/node.socket"
#    ]
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - RESTORE_SNAPSHOT=${RESTORE_SNAPSHOT:-}
      - HASURA_URI=http://hasura:8080
      - METADATA_SERVER_URI=${METADATA_SERVER_URI:-https://tokens.cardano.org}
      - OGMIOS_HOST=cardano-node-ogmios
      - CACHE_ENABLED=true
      - CARDANO_NODE_CONFIG_PATH=/config/config.json
      - RESTORE_RECREATE_DB=N
    depends_on:
      - hasura
      - cardano-node-ogmios
      - postgres
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - ./config/network/${NETWORK:-preview}:/config/cardano-node
      - db-sync-data:/var/lib/cexplorer
      - node-ipc:/node-ipc
    restart: on-failure
    stop_signal: SIGINT
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  hasura:
    image: inputoutput/cardano-graphql-hasura:${CARDANO_GRAPHQL_VERSION:-8.0.0}
    platform: ${PLATFORM:-linux/x86_64}
    ports:
      - ${HASURA_PORT:-8090}:8080
    depends_on:
      - "postgres"
    restart: on-failure
    environment:
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_CORS_DOMAIN=http://localhost:9695
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  cardano-graphql-server:
    image: inputoutput/cardano-graphql-server:${CARDANO_GRAPHQL_VERSION:-8.0.0}-${NETWORK:-preview}
    platform: ${PLATFORM:-linux/x86_64}
    depends_on:
      - hasura
      - cardano-node-ogmios
    environment:
      - ALLOW_INTROSPECTION=true
      - CACHE_ENABLED=true
      - LOGGER_MIN_SEVERITY=${LOGGER_MIN_SEVERITY:-info}
      - METADATA_SERVER_URI=${METADATA_SERVER_URI:-https://tokens.cardano.org}
    restart: on-failure
    ports:
      - ${GRAPHQL_PORT:-3001}:3001
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

secrets:
  postgres_db:
    file: ./.secrets/postgres_db
  postgres_password:
    file: ./.secrets/postgres_password
  postgres_user:
    file: ./.secrets/postgres_user
volumes:
  db-sync-data:
  node-db:
  node-ipc:
  postgres-data:
