apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $.Chart.Name }}-configmap"
  labels:
    name: "{{ $.Chart.Name }}-configmap"
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $value := .Values.env }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
