apiVersion: v1
kind: Service
metadata:
  name: "{{ $.Chart.Name }}-service"
  namespace: {{ .Values.namespace }}
  labels:
    service: "{{ .Values.labels.service }}"
spec:
  ports:
    - port: 80
      name: node
      targetPort: node
      protocol: TCP
  selector:
    service: "{{ .Values.labels.service }}"
